C;CLCC config menu UI
CommitteeOfZero/impacto pull request #81
Opened 2024-10-16 22:23 UTC by PringlesGang

Will implement the UI for the C;CLCC config menu
(Will do the actual implementation in a separate PR once this is done)

2025-01-03 23:29 UTC, KKhanhH requested changes

2025-01-03 23:29 UTC, KKhanhH commented on src/games/cclcc/optionsmenu.cpp
> +  Pages.push_back(BasicPage);
Do you delete pages elements? probably should make Pages a vector of unique_ptrs so it deletes itself

2025-01-03 23:29 UTC, KKhanhH commented on src/games/cclcc/optionsmenu.cpp
> +  Pages.push_back(BasicPage);
or just store the pages by value in an array tbh. it's fixed anyway

2025-01-03 23:29 UTC, KKhanhH commented on src/games/cclcc/optionsmenu.cpp
> +    Widget* const widget = VoicePage->Children.at(i);
Minor nitpick but you probably don't need .at if you're already checking bounds with for loop anyway + debug mode has the bounds assertions

2025-01-03 23:29 UTC, KKhanhH commented on src/games/cclcc/optionsmenu.cpp
> +    Pages.at(CurrentPage)->Update(dt);
Probably also shouldn't be using at in update loops

2025-01-03 23:29 UTC, KKhanhH commented on src/games/cclcc/optionsmenu.h
> +  inline bool AnyEntrySelected() {
Inline is implicit for class definitions so you don't need it

2025-01-03 23:29 UTC, KKhanhH commented on src/ui/widget.h
> -  virtual void Render() = 0;
I'm not sure how often you would have renderless widgets so I think it would be better to leave the base as abstract so then you get compile errors if you don't define it. For clickbutton you could just add an empty override.

2025-01-03 23:29 UTC, KKhanhH commented on src/ui/widgets/cclcc/optionsentry.cpp
> +  Audio::Channels[Audio::AC_REV]->Play("sysse", 2, false, 0.0f);
Wrong audio channel

2025-01-03 23:29 UTC, KKhanhH commented on src/util.h
> +  constexpr RectF operator+(RectF const& other) const {
I dont know if I like overloading operator + and operator- for this. Geometrically adding every member of a rectangle doesn't really mean anything and the new rect doesn't really relate much to the originals.

2025-01-03 23:29 UTC, KKhanhH commented on src/vm/inst_misc.cpp
> -      if (!((Interface::PADinputButtonWentDown & Interface::PAD1B) ||
Is this not used in any of the other games as well?

2025-01-07 10:38 UTC, KKhanhH commented on src/ui/widgets/cclcc/optionsvoiceslider.cpp
> +  std::function<void(ClickButton*)> onClick = std::bind(
apparently std::bind is slower than the lambda equivalent so we might want to consider changing these and all the other bind assignments

2025-01-15 01:41 UTC, PringlesGang commented on src/games/cclcc/optionsmenu.cpp
> +  Pages.push_back(BasicPage);
They store unique pointers now

2025-01-15 01:41 UTC, PringlesGang commented on src/games/cclcc/optionsmenu.cpp
> +    Widget* const widget = VoicePage->Children.at(i);
Yeah, I guess debug mode should indeed pick up on that. Changed them all to direct indexing

2025-01-15 01:42 UTC, PringlesGang commented on src/games/cclcc/optionsmenu.cpp
> +    Pages.at(CurrentPage)->Update(dt);
Changed this too

2025-01-15 01:42 UTC, PringlesGang commented on src/games/cclcc/optionsmenu.h
> +  inline bool AnyEntrySelected() {
Oh really? Cool

2025-01-15 01:42 UTC, PringlesGang commented on src/ui/widget.h
> -  virtual void Render() = 0;
Yeah, it's probably better to leave it an opt-out thing, you're right

2025-01-15 01:42 UTC, PringlesGang commented on src/ui/widgets/cclcc/optionsentry.cpp
> +  Audio::Channels[Audio::AC_REV]->Play("sysse", 2, false, 0.0f);
Haha whoops

2025-01-15 01:45 UTC, PringlesGang commented on src/ui/widgets/cclcc/optionsvoiceslider.cpp
> +  std::function<void(ClickButton*)> onClick = std::bind(
Is this a thing I should change here right now, or do we refactor this in bulk later?

2025-01-15 01:51 UTC, PringlesGang commented on src/vm/inst_misc.cpp
> -      if (!((Interface::PADinputButtonWentDown & Interface::PAD1B) ||
From what I could tell from the decomp, case 1 should call the main update loop of the options menu, which we do somewhere else already regardless of the VM.

All this switch case used to do is set `SF_SUBMENUEXIT` based on user input, which every implemented case of the options menu already does in _its_ update loop. It should not be used by any game for which the options menu is implemented.

The only thing I see that _might_ go wrong here, is the instruction passing despite `SF_SUBMENUEXIT` not being triggered yet (which I have fixed now).

2025-01-15 01:56 UTC, PringlesGang commented on src/util.h
> +  constexpr RectF operator+(RectF const& other) const {
I mostly used this overload to add a movement vector to the `RectF`; would it be better I overload `constexpr RectF operator+(const glm::vec2 movement_vector) const` instead, add a `void RectF::Translate(float x, float y)` method, or simply deal with painfully constructing new `RectF`-s like we used to?

2025-01-15 09:34 UTC, KKhanhH commented on src/ui/widgets/cclcc/optionsvoiceslider.cpp
> +  std::function<void(ClickButton*)> onClick = std::bind(
we can just refactor in bulk, i guess i'll do it in my cpp modernizations branch

2025-01-15 19:59 UTC, KKhanhH commented on src/util.h
> +  constexpr RectF operator+(RectF const& other) const {
I think translate using operator+ makes sense with a vec 2

2025-01-18 05:19 UTC, KKhanhH commented on src/games/cclcc/optionsmenu.cpp
> +    glm::vec2 pos = VoicePosition;
You're shadowing pos here

2025-01-18 06:12 UTC, KKhanhH commented on src/games/cclcc/optionsmenu.cpp
> +    glm::vec4 col(1.0f, 1.0f, 1.0f, FadeAnimation.Progress);
Since everything is already being made const, it might not be a bad idea to make col const and maskTint const with const glm::vec4 maskTint = col * glm::vec4{glm::vec3{1}, (float)0xa0 / 0x100}};

2025-01-18 21:08 UTC, PringlesGang commented on src/games/cclcc/optionsmenu.cpp
> +    glm::vec2 pos = VoicePosition;
Oh yeah that can just reuse the old pos. Thanks for the heads-up

2025-01-18 21:08 UTC, PringlesGang commented on src/games/cclcc/optionsmenu.cpp
> +    glm::vec4 col(1.0f, 1.0f, 1.0f, FadeAnimation.Progress);
Good one

2025-01-19 22:14 UTC, KKhanhH approved these changes

2025-01-19 22:16 UTC, merged